spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: "jdbc:mysql://zemoga-test-db.crhpedy9xxto.us-east-1.rds.amazonaws.com:3306/portfolioDB"
    username: zemoga_test_db
    password: Zem0ga.101
    driver-class-name: 'com.mysql.jdbc.Driver'